-- Rulează în Supabase → SQL Editor (o singură dată, sau ajustează cu ALTER dacă tabela există deja).
-- Formularul site-ului inserează prin API cu service role în `public.clients`.

CREATE TABLE IF NOT EXISTS public.clients (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NULL DEFAULT now(),
    name text NOT NULL,
    phone text NOT NULL DEFAULT '',
    email text NOT NULL DEFAULT '',
    county text NOT NULL DEFAULT '',
    hectares numeric NOT NULL DEFAULT 0,
    crops jsonb NOT NULL DEFAULT '[]'::jsonb,
    urgency text NOT NULL DEFAULT '',
    subsidy_income numeric NOT NULL DEFAULT 0,
    fuel_savings numeric NOT NULL DEFAULT 0,
    total_benefit numeric NOT NULL DEFAULT 0,
    notes text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'Lead',
    source text NOT NULL DEFAULT 'Website Form',
    is_new boolean NOT NULL DEFAULT true,
    product_name text NULL
);

CREATE INDEX IF NOT EXISTS idx_clients_status ON public.clients (status);
CREATE INDEX IF NOT EXISTS idx_clients_created_at ON public.clients (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_clients_is_new ON public.clients (is_new) WHERE is_new = true;

ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;

-- API-ul folosește cheia service_role; rolul acesta ocolește RLS în Supabase.
-- Dacă vezi erori „permission denied” fără service role, verifică variabila SUPABASE_SERVICE_ROLE_KEY pe Vercel.

-- Opțional: acces doar pentru utilizatori autentificați (tabele admin), dacă folosești anon key direct:
-- CREATE POLICY "authenticated_select_clients"
--   ON public.clients FOR SELECT TO authenticated USING (true);

COMMENT ON TABLE public.clients IS 'Lead-uri din formulare site (Contact, ROI) — CRM / notificări.';

-- Dacă `clients` există deja (Ai adăugat manual coloane), adaugă doar ce lipsește:
-- ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS hectares numeric NOT NULL DEFAULT 0;
-- ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS crops jsonb NOT NULL DEFAULT '[]'::jsonb;
-- ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS urgency text NOT NULL DEFAULT '';
-- ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS subsidy_income numeric NOT NULL DEFAULT 0;
-- ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS fuel_savings numeric NOT NULL DEFAULT 0;
-- ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS total_benefit numeric NOT NULL DEFAULT 0;
-- ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'Website Form';
-- ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS is_new boolean NOT NULL DEFAULT true;
-- ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS product_name text NULL;
-- ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
